version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/samples/lib/spa-angular-client"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
